# Generated by Django 3.2.25 on 2026-02-07 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('config_value', models.CharField(max_length=200, verbose_name='配置值')),
                ('description', models.TextField(blank=True, verbose_name='配置描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '行为分析配置',
                'verbose_name_plural': '行为分析配置',
                'ordering': ['config_key'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_type', models.CharField(choices=[('faq', '常见问题'), ('rule', '平台规则'), ('tip', '交易技巧'), ('other', '其他')], max_length=20, verbose_name='知识类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='商品标题')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('condition', models.CharField(choices=[('new', '全新'), ('like_new', '几乎全新'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], max_length=20, verbose_name='商品状况')),
                ('status', models.CharField(choices=[('available', '可交易'), ('sold', '已售出'), ('reserved', '已预订')], default='available', max_length=20, verbose_name='交易状态')),
                ('location', models.CharField(max_length=100, verbose_name='交易地点')),
                ('contact_info', models.CharField(max_length=200, verbose_name='联系方式')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品图片')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.category', verbose_name='分类')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '二手商品',
                'verbose_name_plural': '二手商品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warning_type', models.CharField(choices=[('abnormal_behavior', '异常行为警告'), ('risk_threshold', '风险阈值警告'), ('other', '其他警告')], max_length=20, verbose_name='警告类型')),
                ('warning_content', models.TextField(verbose_name='警告内容')),
                ('warning_time', models.DateTimeField(auto_now_add=True, verbose_name='警告时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '警告通知',
                'verbose_name_plural': '警告通知',
                'ordering': ['-warning_time'],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('browse', '浏览'), ('click', '点击'), ('submit', '提交表单'), ('transaction', '交易'), ('favorite', '收藏'), ('message', '发送消息'), ('review', '评价'), ('other', '其他')], max_length=20, verbose_name='行为类型')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='行为时间')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='来源URL')),
                ('action_data', models.TextField(blank=True, null=True, verbose_name='行为数据')),
                ('session_id', models.CharField(max_length=100, verbose_name='会话ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'ordering': ['-action_time'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='密钥')),
                ('recovery_codes', models.TextField(blank=True, null=True, verbose_name='恢复代码')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '双因素认证',
                'verbose_name_plural': '双因素认证',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易价格')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='交易状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product', verbose_name='商品')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='日志时间')),
                ('log_level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='info', max_length=20, verbose_name='日志级别')),
                ('log_type', models.CharField(choices=[('abnormal_behavior', '异常行为识别'), ('warning_notification', '警告通知'), ('report_submission', '异常报告提交'), ('admin_action', '管理员操作'), ('system_event', '系统事件')], max_length=50, verbose_name='日志类型')),
                ('description', models.TextField(verbose_name='日志描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('request_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='请求路径')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='附加数据')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='相关用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-log_time'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('2fa_setup', '双因素认证设置'), ('2fa_verify', '双因素认证验证'), ('password_change', '密码修改'), ('suspicious', '可疑操作')], max_length=20, verbose_name='日志类型')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '安全日志',
                'verbose_name_plural': '安全日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(max_length=20, verbose_name='推荐类型')),
                ('score', models.FloatField(verbose_name='推荐分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '推荐日志',
                'verbose_name_plural': '推荐日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product', verbose_name='相关商品')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EncryptedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50, verbose_name='数据类型')),
                ('encrypted_value', models.TextField(verbose_name='加密值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_data', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '加密数据',
                'verbose_name_plural': '加密数据',
            },
        ),
        migrations.CreateModel(
            name='BehaviorReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_content', models.TextField(verbose_name='报告内容')),
                ('total_score', models.IntegerField(verbose_name='累计风险分数')),
                ('report_time', models.DateTimeField(auto_now_add=True, verbose_name='报告时间')),
                ('admin_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='处理状态')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reports', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_reports', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '异常行为报告',
                'verbose_name_plural': '异常行为报告',
                'ordering': ['-report_time'],
            },
        ),
        migrations.CreateModel(
            name='AbnormalBehavior',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('abnormal_type', models.CharField(choices=[('login', '异常登录'), ('frequency', '异常操作频率'), ('transaction', '异常交易金额'), ('automation', '脚本自动化操作'), ('other', '其他异常')], max_length=20, verbose_name='异常类型')),
                ('risk_score', models.IntegerField(default=0, verbose_name='风险分值')),
                ('detected_time', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('is_warned', models.BooleanField(default=False, verbose_name='已发送警告')),
                ('is_reported', models.BooleanField(default=False, verbose_name='已上报管理员')),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.userbehavior', verbose_name='关联行为')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_behaviors', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '异常行为',
                'verbose_name_plural': '异常行为',
                'ordering': ['-detected_time'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_score', models.FloatField(default=0.0, verbose_name='偏好分数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.category', verbose_name='分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], verbose_name='评分')),
                ('comment', models.TextField(verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product', verbose_name='相关商品')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='被评价者')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价者')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'ordering': ['-created_at'],
                'unique_together': {('reviewer', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
