# Generated by Django 3.2.25 on 2026-02-07 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypteddata',
            name='iv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='初始化向量'),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='details',
            field=models.TextField(blank=True, verbose_name='详细信息'),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='is_successful',
            field=models.BooleanField(default=True, verbose_name='是否成功'),
        ),
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0, verbose_name='相似度分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_products1', to='marketplace.product', verbose_name='商品1')),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_products2', to='marketplace.product', verbose_name='商品2')),
            ],
            options={
                'verbose_name': '商品相似度',
                'verbose_name_plural': '商品相似度',
                'unique_together': {('product1', 'product2')},
            },
        ),
    ]
