# Generated by Django 3.2.25 on 2026-03-06 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0003_auto_20260306_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='余额')),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='冻结余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户钱包',
                'verbose_name_plural': '用户钱包',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('recharge', '充值'), ('withdraw', '提现'), ('payment', '支付'), ('refund', '退款'), ('income', '收入'), ('freeze', '冻结'), ('unfreeze', '解冻')], max_length=20, verbose_name='交易类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易前余额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易后余额')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.transaction', verbose_name='关联交易')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.wallet', verbose_name='钱包')),
            ],
            options={
                'verbose_name': '钱包交易记录',
                'verbose_name_plural': '钱包交易记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('wallet', '钱包支付'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('bank', '银行卡')], max_length=20, verbose_name='支付方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='状态')),
                ('third_party_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='第三方交易ID')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='marketplace.transaction', verbose_name='关联交易')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='marketplace_wallet__06a1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='marketplace_status_ff003e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction'], name='marketplace_transac_0f7e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='marketplace_status_965bdd_idx'),
        ),
    ]
